set(CPACK_GENERATOR "DEB;TGZ")
set(CPACK_PACKAGE_VERSION_MAJOR ${APPLICATION_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${APPLICATION_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${APPLICATION_VERSION_PATCH})
set(CPACK_DEBIAN_PACKAGE_DEPENDS "")
set(CPACK_PACKAGE_DESCRIPTION "Test")
set(CPACK_PACKAGE_CONTACT "opsise")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/Debian/postinst")

set(CPACK_PACKAGING_INSTALL_PREFIX "/data")

set(package_suffix ".toto")


set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")


string(TOLOWER "${CPACK_PACKAGE_NAME}" CPACK_PACKAGE_NAME_LOWERCASE)
find_program(DPKG_PROGRAM dpkg DOC "dpkg program of Debian-based systems")
if(DPKG_PROGRAM)
  execute_process(
    COMMAND ${DPKG_PROGRAM} --print-architecture
    OUTPUT_VARIABLE CPACK_DEBIAN_PACKAGE_ARCHITECTURE
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
endif(DPKG_PROGRAM)

IF (${PROJECT_TYPE} STREQUAL "LIBRARY")
  set(CPACK_PACKAGE_FILE_NAME "lib${CPACK_PACKAGE_NAME_LOWERCASE}-${APPLICATION_VERSION_STRING}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")   
ENDIF(${PROJECT_TYPE} STREQUAL "LIBRARY")

IF (${PROJECT_TYPE} STREQUAL "EXECUTABLE")
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME_LOWERCASE}-${APPLICATION_VERSION_STRING}-${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")  
ENDIF(${PROJECT_TYPE} STREQUAL "EXECUTABLE")
include(CPack)